services:
  - type: worker
    name: plant-health-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        fromSecret: true
      - key: PLANT_API_KEY
        fromSecret: true
      - key: TREFLE_API_KEY
        fromSecret: true